version: "4.24.2"
services:
  app:  
    build: .
    ports:
      - "3000:3000" 
    links:
      - mongDB
  mongDB:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tefa  
      - MONGO_INITDB_ROOT_PASSWORD=123456789 